const String kstringsearch = 'Hokkaido, Sapporo';
const String kstringshometopbox = 'May 26, 2022 (Wood)';
const String kappstringsbox1title = '介護有料老人ホームひまわり倶楽部の介護職／ヘルパー求人（パート／バイト）';
const String kappstringsbox1pay = '¥ 6,000';
const String kappstringsbox1d2 = '介護付き有料老人ホーム';
const String kappstringsbox1d3 = '5月 31日（水）08 : 00 ~ 17 : 00';
const String kappstringsbox1d4 = '北海道札幌市東雲町3丁目916番地17号';
const String kappstringsbox1d5 = '交通費 300円';
const String kappstringsbox1d6 = '住宅型有料老人ホームひまわり倶楽部';
